import type { MissionTemplate } from '../models/types';

export const MISSION_TEMPLATES: MissionTemplate[] = [
  // destroy
  {
    type: 'destroy',
    description: 'Destroy 5 enemies.',
    difficulty: 'easy',
    xpReward: 30,
    coinReward: 10,
    target: 5,
    timeLimitSec: 60,
    minLevel: 0,
  },
  {
    type: 'destroy',
    description: 'Destroy 15 enemies.',
    difficulty: 'medium',
    xpReward: 80,
    coinReward: 25,
    target: 15,
    timeLimitSec: 60,
    minLevel: 2,
  },
  {
    type: 'destroy',
    description: 'Destroy 30 enemies.',
    difficulty: 'hard',
    xpReward: 150,
    coinReward: 50,
    target: 30,
    timeLimitSec: 90,
    minLevel: 5,
  },

  // survive
  {
    type: 'survive',
    description: 'Survive for 30 seconds.',
    difficulty: 'easy',
    xpReward: 10,
    coinReward: 20,
    target: 30,
    timeLimitSec: 30,
    minLevel: 0,
  },
  {
    type: 'survive',
    description: 'Survive for 60 seconds.',
    difficulty: 'medium',
    xpReward: 25,
    coinReward: 50,
    target: 60,
    timeLimitSec: 60,
    minLevel: 2,
  },
  {
    type: 'survive',
    description: 'Survive for 90 seconds.',
    difficulty: 'hard',
    xpReward: 50,
    coinReward: 100,
    target: 90,
    timeLimitSec: 90,
    minLevel: 5,
  },

  // collect
  {
    type: 'collect',
    description: 'Collect 10 items.',
    difficulty: 'easy',
    xpReward: 20,
    coinReward: 15,
    target: 10,
    minLevel: 0,
  },
  {
    type: 'collect',
    description: 'Collect 25 items.',
    difficulty: 'medium',
    xpReward: 50,
    coinReward: 40,
    target: 25,
    minLevel: 2,
  },
  {
    type: 'collect',
    description: 'Collect 50 items.',
    difficulty: 'hard',
    xpReward: 100,
    coinReward: 80,
    target: 50,
    minLevel: 5,
  },

  // distance
  {
    type: 'distance',
    description: 'Travel 1000 units.',
    difficulty: 'easy',
    xpReward: 25,
    coinReward: 10,
    target: 1000,
    minLevel: 0,
  },
  {
    type: 'distance',
    description: 'Travel 3000 units.',
    difficulty: 'medium',
    xpReward: 60,
    coinReward: 30,
    target: 3000,
    minLevel: 2,
  },
  {
    type: 'distance',
    description: 'Travel 5000 units.',
    difficulty: 'hard',
    xpReward: 120,
    coinReward: 60,
    target: 5000,
    minLevel: 5,
  },

  // escort
  {
    type: 'escort',
    description: 'Escort the convoy for 30 seconds.',
    difficulty: 'easy',
    xpReward: 10,
    coinReward: 25,
    target: 30,
    timeLimitSec: 30,
    minLevel: 0,
  },
  {
    type: 'escort',
    description: 'Escort the convoy for 60 seconds.',
    difficulty: 'medium',
    xpReward: 30,
    coinReward: 60,
    target: 60,
    timeLimitSec: 60,
    minLevel: 2,
  },
  {
    type: 'escort',
    description: 'Escort the convoy for 90 seconds.',
    difficulty: 'hard',
    xpReward: 60,
    coinReward: 120,
    target: 90,
    timeLimitSec: 90,
    minLevel: 5,
  },
];
